spring:
  output:
    ansi:
      enabled: ALWAYS
  application:
    name: libraryapi
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
  #   ddl-auto: update
      ddl-auto: none # com none temos controle total (podendo dar sql comandos manuais)
    properties:
      hibernate.format_sql: true